### ISSUE TITLE
cronjob could not be applied

### ISSUE THREAD

**Issue by gecube** [eftechcombr/glpi#57]
```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: mariadb-timezone
  namespace: glpi
spec:
  template:
    spec:
      containers:
      - image: mariadb:10.6
        imagePullPolicy: IfNotPresent
        name: base
        command:
        - sh 
        - -c
        - "mysql -h $MARIADB_HOST -u root -p$MARIADB_ROOT_PASSWORD -e \"GRANT SELECT ON \`mysql\`.\`time_zone_name\` TO 'glpi'@'%'; FLUSH PRIVILEGES; FLUSH PRIVILEGES;\""
        envFrom:
        - secretRef:
            name: mariadb-glpi-secret
      restartPolicy: Never
  backoffLimit: 5
status: {}
```

this manifest yields this error:

``` bash
$ kubectl apply -f mariadb-job.yaml --dry-run=client
error: error parsing mariadb-job.yaml: error converting YAML to JSON: yaml: line 16: found unknown escape character
```

I just cloned this repo, so it could not be an issue with kubectl.

```bash
$kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.4", GitCommit:"fa3d7990104d7c1f16943a67f11b154b71f6a132", GitTreeState:"clean", BuildDate:"2023-07-19T12:14:48Z", GoVersion:"go1.20.6", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.2", GitCommit:"7f6f68fdabc4df88cfea2dcf9a19b2b830f1e647", GitTreeState:"clean", BuildDate:"2023-05-17T14:13:28Z", GoVersion:"go1.20.4", Compiler:"gc", Platform:"linux/arm64"}
```
