### ISSUE TITLE
Move plugins catalogue /var/www/html/plugins/ to PVC

### ISSUE THREAD

**Issue by gecube** [eftechcombr/glpi#64]
If I am restarting pod with php-fpm, the plugins directory is emptied. I want to get **persistence** of installed plugins from other git repos like https://github.com/derricksmith/phpsaml/tree/Version-1.3.0

**Comment by eduardofraga** [comment]
Can you check `./kubernetes/glpi-persistentvolumeclaim.yaml`?

**Comment by gecube** [comment]
Hi @eduardofraga 

Thanks for the fast reaction.

I see that you are mounting only the next catalogues:

```
        - name: files 
          mountPath: /var/lib/glpi
        - name: etc 
          mountPath: /etc/glpi
        - name: marketplace
          mountPath: /var/www/html/marketplace
```

I need to directly install plugin. Accidentally I found that they should be installed to `/var/www/html/plugins/` (is it correct?) and it is not mounted like PVC.

> Can you check ./kubernetes/glpi-persistentvolumeclaim.yaml?

yes, I checked. I am not talking about marketplace, but rather 'common' plugins. Installed from git repo into separate catalogue.

**Comment by eduardofraga** [comment]
Ok @gecube 

Configure the plugin directory in configmap: `./kubernetes/glpi-configmap.yaml` 

```
apiVersion: v1
kind: ConfigMap
metadata: 
  name: glpi-config
  namespace: glpi 
data: 
  ...
  ...
  GLPI_MARKETPLACE_DIR: /var/www/html/marketplace
  ...
  ...
  GLPI_PLUGIN_DOC_DIR: /var/lib/glpi/_plugins
```

The content of `/var/lib/glpi` is persisted on PVC glpi-files:

```
        volumeMounts:
        - name: files 
          mountPath: /var/lib/glpi
        - name: etc 
          mountPath: /etc/glpi
        - name: marketplace
          mountPath: /var/www/html/marketplace
        resources: {}
      volumes: 
      - name: etc 
        persistentVolumeClaim: 
          claimName: glpi-etc 
      - name: files
        persistentVolumeClaim:
          claimName: glpi-files
      - name: marketplace
        persistentVolumeClaim:
          claimName: glpi-marketplace
```
